# Generated by Django 4.1.2 on 2022-10-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_rename_expensecategory_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
