# Generated by Django 4.1.2 on 2022-10-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0004_expense_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Article",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
    ]
