# Generated by Django 4.1.2 on 2022-10-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0005_delete_article_delete_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
