# Generated by Django 4.1.2 on 2022-10-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="income",
            name="source",
        ),
    ]
