# Generated by Django 4.1.2 on 2022-10-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0002_remove_income_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="income",
            name="frequency",
        ),
    ]
